### ISSUE TITLE
regexp search: \n* not found

### ISSUE THREAD

**Issue by Fuco1** [Malabarba/ox-jekyll-subtree#1]
This happens due to the last ine of `endless/prepare-input-buffer` which, I guess, should skip to the next headline?

Maybe it would be safer to use `outline-next-heading` as it handles the case when there is nothing _after_ the current heading (or it raises an error you can process).

This is really low-priority task though, so don't worry over it.

**Comment by Malabarba** [comment]
Thanks for catching that! It was a simple fix. (Hopefully... it did fix it, right?)
