### ISSUE TITLE
Backend issue with org-mode 9.0

### ISSUE THREAD

**Issue by despresT** [Malabarba/ox-jekyll-subtree#7]
In the ox-jekyll.el file, line 95, there is a ": export-block" in the org-export-define-derived-backend function. When using org-mode version 9.0 or above (I am using org-mode 9.0.2), the export-block synthax changed (see http://thread.gmane.org/gmane.emacs.orgmode/103736). However, I have never experience Lisp coding, and cannot solve this issue by myself. Could you help me?
Thank you, 
T.

**Comment by ctgnauh** [comment]
I deleted this line and now it works fine.

Hope this can help you...

**Comment by despresT** [comment]
Thank you, the issue is now fix and everything is working, however, I have another one.
When I load emacs, know I have `Symbol's value as variable is void: endless/export-to-blog.`
However, the script is working (I was able to change an org subtree into an html file).
Any idea to remove this warning message from emacs?

Here is in my .emacs file: 

```
(load-file "~/.emacs.d/lisp/ox-jekyll.el")
(load-file "~/.emacs.d/lisp/ox-jekyll-subtree.el")
(autoload endless/export-to-blog "jekyll-once")
(setq org-jekyll-use-src-plugin t)
 
;; Obviously, these two need to be changed for your blog.
(setq endless/blog-base-url "http://myblog.org/")
(setq endless/blog-dir (expand-file-name "~/blog/"))
```

**Comment by ctgnauh** [comment]
Make sure `ox-jekyll-subtree` in your `load-path`.

And replace this line
```(autoload endless/export-to-blog "jekyll-once")```
with 
```(autoload 'endless/export-to-blog "ox-jekyll-subtree")```

**Comment by despresT** [comment]
Perfect. It work like a charm.
Many thanks for your help.
