### ISSUE TITLE
org v9: unavailable ":export-block" 

### ISSUE THREAD

**Issue by vindarel** [Malabarba/ox-jekyll-subtree#8]
Hi,
when upgrading to org v9, I hit [this issue](https://github.com/marsmining/ox-twbs/issues/13): the backend `(org-export-define-derived-backend 'jekyll 'html` doesn't accept the keyword `:export-block` any more. I commented it out.

**Comment by ctgnauh** [comment]
Same problem: #7

**Comment by Malabarba** [comment]
Should be fixed now.
