### ISSUE TITLE
Bump ox-jekill.el

### ISSUE THREAD

**Issue by arichiardi** [Malabarba/ox-jekyll-subtree#9]
Greetings great @Malabarba!

I am not using this yet, but I have to say that after having read your blog post I am pretty sold 😀
I was just wondering one thing, I see that the `ox-jekill.el` file is old and has not been following up its counterpart.
I was wondering whether you'd want to either copy it over from there or even `git submodule` it, so that they will always be in sync.

Thanks a lot for this and other impressive Emacs stuff!

**Comment by Malabarba** [comment]
Done :+1:
